export const ketubeExceptionCode = {
  UNAUTHORIZED: "UNAUTHORIZED",
  HTTP_500: "HTTP_500",
  PLEASE_GO_TO_SIGN_UP_WITH_GOOGLE_ACCOUNT:
    "PLEASE_GO_TO_SIGN_UP_WITH_GOOGLE_ACCOUNT",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  FAVORITE_ARTIST_IS_ALREADY: "FAVORITE_ARTIST_IS_ALREADY",
  VIDEO_NOT_FOUND: "VIDEO_NOT_FOUND",
  VIDEO_NAME_IS_UNIQUE: "VIDEO_NAME_IS_UNIQUE",
  VIDEO_NAME_AND_ALBUM_AND_ARTIST_IS_UNIQUE:
    "VIDEO_NAME_AND_ALBUM_AND_ARTIST_IS_UNIQUE",
  VIDEO_SLUG_IS_UNIQUE: "VIDEO_SLUG_IS_UNIQUE",
  VIDEO_SLUG_AND_ALBUM_AND_ARTIST_IS_UNIQUE:
    "VIDEO_SLUG_AND_ALBUM_AND_ARTIST_IS_UNIQUE",
  VIDEO_FILE_TYPE_IS_NOT_SUPPORT: "VIDEO_FILE_TYPE_IS_NOT_SUPPORT",
  VIDEO_FILE_IS_TO_LARGE: "VIDEO_FILE_IS_TO_LARGE",
  RELEASE_DATE_IS_THAN_PUBLISHED_DATE: "RELEASE_DATE_IS_THAN_PUBLISHED_DATE",
  ALBUM_NAME_IS_UNIQUE: "ALBUM_NAME_IS_UNIQUE",
  ALBUM_SLUG_IS_UNIQUE: "ALBUM_SLUG_IS_UNIQUE",
  PLAYLIST_NAME_IS_UNIQUE: "PLAYLIST_NAME_IS_UNIQUE",
  PLAYLIST_SLUG_IS_UNIQUE: "PLAYLIST_SLUG_IS_UNIQUE",
};
