services:
  client:
    build:
      context: ./
      dockerfile: ./docker/local/Dockerfile
    container_name: ketube-client
    ports:
      - 0.0.0.0:3000:4280
    networks:
      - ketube-networks

networks:
  ketube-networks:
